// <auto-generated />
using System;
using FormDesignerAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormDesignerAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217180342_AddProjectContext")]
    partial class AddProjectContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormDesignerAPI.Core.CodeGenerationContext.Aggregates.CodeGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormRevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutputFolderPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("ProcessingDuration")
                        .HasColumnType("time");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ZipFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("ZipFileSizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CodeGenerationJobs", (string)null);
                });

            modelBuilder.Entity("FormDesignerAPI.Core.FormContext.Aggregates.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DefinitionSchema");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("FormDesignerAPI.Core.FormContext.Aggregates.FormRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DefinitionSchema");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("Version");

                    b.HasIndex("FormId", "Version")
                        .IsUnique();

                    b.ToTable("FormRevisions", (string)null);
                });

            modelBuilder.Entity("FormDesignerAPI.Core.ProjectContext.Aggregates.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("_codeGenerationJobIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodeGenerationJobIds");

                    b.Property<string>("_formIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FormIds");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("FormDesignerAPI.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FormDesignerAPI.Core.CodeGenerationContext.Aggregates.CodeGenerationJob", b =>
                {
                    b.OwnsOne("FormDesignerAPI.Core.CodeGenerationContext.ValueObjects.GenerationOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("CodeGenerationJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdditionalImports")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_AdditionalImports");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_Author");

                            b1.Property<string>("CustomSettings")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_CustomSettings");

                            b1.Property<string>("DatabaseType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_DatabaseType");

                            b1.Property<bool>("GenerateIntegrationTests")
                                .HasColumnType("bit")
                                .HasColumnName("Options_GenerateIntegrationTests");

                            b1.Property<bool>("IncludeCSharpModels")
                                .HasColumnType("bit")
                                .HasColumnName("Options_IncludeCSharpModels");

                            b1.Property<bool>("IncludeReactComponents")
                                .HasColumnType("bit")
                                .HasColumnName("Options_IncludeReactComponents");

                            b1.Property<bool>("IncludeSqlSchema")
                                .HasColumnType("bit")
                                .HasColumnName("Options_IncludeSqlSchema");

                            b1.Property<bool>("IncludeTests")
                                .HasColumnType("bit")
                                .HasColumnName("Options_IncludeTests");

                            b1.Property<string>("Namespace")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_Namespace");

                            b1.Property<string>("ProjectName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_ProjectName");

                            b1.Property<string>("TestFramework")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Options_TestFramework");

                            b1.Property<bool>("UseFluentAssertions")
                                .HasColumnType("bit")
                                .HasColumnName("Options_UseFluentAssertions");

                            b1.HasKey("CodeGenerationJobId");

                            b1.ToTable("CodeGenerationJobs");

                            b1.WithOwner()
                                .HasForeignKey("CodeGenerationJobId");
                        });

                    b.OwnsOne("FormDesignerAPI.Core.CodeGenerationContext.ValueObjects.GenerationVersion", "Version", b1 =>
                        {
                            b1.Property<Guid>("CodeGenerationJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Major")
                                .HasColumnType("int")
                                .HasColumnName("Version_Major");

                            b1.Property<int>("Minor")
                                .HasColumnType("int")
                                .HasColumnName("Version_Minor");

                            b1.Property<int>("Patch")
                                .HasColumnType("int")
                                .HasColumnName("Version_Patch");

                            b1.HasKey("CodeGenerationJobId");

                            b1.ToTable("CodeGenerationJobs");

                            b1.WithOwner()
                                .HasForeignKey("CodeGenerationJobId");
                        });

                    b.Navigation("Options")
                        .IsRequired();

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("FormDesignerAPI.Core.FormContext.Aggregates.Form", b =>
                {
                    b.OwnsOne("FormDesignerAPI.Core.FormContext.ValueObjects.OriginMetadata", "Origin", b1 =>
                        {
                            b1.Property<Guid>("FormId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Origin_CreatedAt");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Origin_CreatedBy");

                            b1.Property<string>("ReferenceId")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Origin_ReferenceId");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("Origin_Type");

                            b1.HasKey("FormId");

                            b1.ToTable("Forms");

                            b1.WithOwner()
                                .HasForeignKey("FormId");
                        });

                    b.Navigation("Origin")
                        .IsRequired();
                });

            modelBuilder.Entity("FormDesignerAPI.Core.FormContext.Aggregates.FormRevision", b =>
                {
                    b.HasOne("FormDesignerAPI.Core.FormContext.Aggregates.Form", null)
                        .WithMany("Revisions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormDesignerAPI.Core.ProjectContext.Aggregates.Project", b =>
                {
                    b.OwnsOne("FormDesignerAPI.Core.ProjectContext.ValueObjects.ProjectFilter", "Filter", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("ActiveOnly")
                                .HasColumnType("bit")
                                .HasColumnName("Filter_ActiveOnly");

                            b1.Property<string>("CustomFilters")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Filter_CustomFilters");

                            b1.Property<string>("FormType")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Filter_FormType");

                            b1.Property<DateTime?>("FromDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Filter_FromDate");

                            b1.Property<string>("Tags")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Filter_Tags");

                            b1.Property<DateTime?>("ToDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Filter_ToDate");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Filter")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FormDesignerAPI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FormDesignerAPI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormDesignerAPI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FormDesignerAPI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormDesignerAPI.Core.FormContext.Aggregates.Form", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
